# Generated by Django 4.1 on 2022-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_hotel_room_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_booked',
            field=models.IntegerField(default=1),
        ),
    ]
