# Generated by Django 4.1 on 2022-10-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_booking_room_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='leave_at',
            new_name='CheckIn',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_at',
            new_name='CheckOut',
        ),
    ]
