# Generated by Django 4.1 on 2022-10-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='CheckIn',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckOut',
            field=models.DateField(),
        ),
    ]
